backcast_loss_ratio: 0.0
context_length: 140
dropout: 0.1
expansion_coefficient_lengths:
- 2
- 2
learning_rate: 0.0001
log_gradient_flow: false
log_interval: -1
log_val_interval: 1
logging_metrics: !!python/object:torch.nn.modules.container.ModuleList
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - '0'
      - !!python/object:pytorch_forecasting.metrics.MAPE
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _cache: null
        _computed: null
        _defaults:
          lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
              ZQpxAVgPAAAAMTA1NTUzMTQzNTMyMDMycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
              NTUzMTQzNTMyMDMycQFhLgEAAAAAAAAAAAAAAAAAAAA=
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
          losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDwAAADEwNTU1MzE0MzUzMTk1MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
              NTU1MzE0MzUzMTk1MnEBYS4BAAAAAAAAAAAAAAA=
          - 0
          - !!python/tuple []
          - !!python/tuple []
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        _device: !!python/object/apply:torch.device
        - cpu
        _enable_grad: false
        _forward_cache: null
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _is_synced: false
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _persistent:
          lengths: false
          losses: false
        _reductions:
          lengths: &id001 !!python/name:torchmetrics.utilities.data.dim_zero_sum ''
          losses: *id001
        _should_unsync: true
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _to_sync: true
        _update_called: false
        compute_on_cpu: false
        dist_sync_fn: null
        dist_sync_on_step: false
        lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
            ZQpxAVgPAAAAMTA1NTUzMTQzNTMyMTkycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
            NTUzMTQzNTMyMTkycQFhLgEAAAAAAAAAAAAAAAAAAAA=
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
        losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
        - !!python/object/apply:torch.storage._load_from_bytes
          - !!binary |
            gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
            AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
            aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
            Z2UKcQFYDwAAADEwNTU1MzE0MzUzMjExMnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
            NTU1MzE0MzUzMjExMnEBYS4BAAAAAAAAAAAAAAA=
        - 0
        - !!python/tuple []
        - !!python/tuple []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
        name: MAPE
        process_group: null
        quantiles: null
        reduction: mean
        training: true
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: true
loss: !!python/object:pytorch_forecasting.metrics.MASE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _cache: null
  _computed: null
  _defaults:
    lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
        ZQpxAVgPAAAAMTA1NTUzMTQzNTMxNzEycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
        NTUzMTQzNTMxNzEycQFhLgEAAAAAAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
    losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
    - !!python/object/apply:torch.storage._load_from_bytes
      - !!binary |
        gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
        AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
        aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
        Z2UKcQFYDwAAADEwNTU1MzE0MzUzMTYzMnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
        NTU1MzE0MzUzMTYzMnEBYS4BAAAAAAAAAAAAAAA=
    - 0
    - !!python/tuple []
    - !!python/tuple []
    - false
    - !!python/object/apply:collections.OrderedDict
      - []
  _device: !!python/object/apply:torch.device
  - cpu
  _enable_grad: false
  _forward_cache: null
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _is_synced: false
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _persistent:
    lengths: false
    losses: false
  _reductions:
    lengths: *id001
    losses: *id001
  _should_unsync: true
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _to_sync: true
  _update_called: false
  compute_on_cpu: false
  dist_sync_fn: null
  dist_sync_on_step: false
  lengths: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApMb25nU3RvcmFn
      ZQpxAVgPAAAAMTA1NTUzMTQzNTMxODcycQJYAwAAAGNwdXEDSwFOdHEEUS6AAl1xAFgPAAAAMTA1
      NTUzMTQzNTMxODcycQFhLgEAAAAAAAAAAAAAAAAAAAA=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  losses: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYDwAAADEwNTU1MzE0MzUzMTc5MnECWAMAAABjcHVxA0sBTnRxBFEugAJdcQBYDwAAADEw
      NTU1MzE0MzUzMTc5MnEBYS4BAAAAAAAAAAAAAAA=
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  name: MASE
  process_group: null
  quantiles: null
  reduction: mean
  training: true
monotone_constaints: {}
num_block_layers:
- 2
- 2
num_blocks:
- 2
- 2
optimizer: ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  eps: 1.0e-08
  groups:
  - series_id
  method: standard
  missing_:
    center: 2797.665251568521
    scale: 802.1766410750931
  norm_: !!python/object:pandas.core.frame.DataFrame
    _flags:
      allows_duplicate_labels: true
    _metadata: []
    _mgr: !!python/object/apply:pandas.core.internals.managers.BlockManager
    - !!python/tuple
      - !!python/object/apply:pandas._libs.internals._unpickle_block
        - !!python/object/apply:numpy.core.multiarray._reconstruct
          args:
          - &id002 !!python/name:numpy.ndarray ''
          - !!python/tuple
            - 0
          - !!binary |
            Yg==
          state: !!python/tuple
          - 1
          - !!python/tuple
            - 2
            - 30
          - !!python/object/apply:numpy.dtype
            args:
            - f8
            - false
            - true
            state: !!python/tuple
            - 3
            - <
            - null
            - null
            - null
            - -1
            - -1
            - 0
          - false
          - !!binary |
            iVv28r9Pu0BMkwHmLK+ZQLmfDoziW6hAMI/j81ObukAZN1rdQZiRQJKa8pnZOqtAsTBJo76VwkD6
            S2btX5KbQJX4fX9Ha7VAJz2r5tqHrUDtG/8T43GOQOlxe0w9HJlArYew0BB0skARLBCjg9iKQOgX
            U0DDhaRAfnsnLCBguEDlkbgo2LCVQBxZeUaHOKhATZLZmeOjtEDqhkndna6UQCpJ1HI2yqRA9Kay
            rs5DtUBJ+FvmrwKTQBXzX8s7xqJAFfaJmvGFu0DBL0VA5fiGQHrA4MRy7KZAVXetNKPltUDXWCb5
            eIiKQACIobXRlqJA+GSKMyUvm0DMQkZhLV2BQNwaTOpBuI9A8FqLXqL/mkCBVEc1IMR0QEvZWUdn
            AJJAxqrV6lVNnkAS1Ds55LGAQITu1M4LnZdAeg+utJdlh0CCYkpy2bx0QGbwwhAQW3tAztYE7X/s
            jkDrcx3z329yQHfrA7iUeYlACPaLATCwk0DqpKADbQB8QOp5GUEtnIlABGUL8i/xkUBb3OcoiXWE
            QPf+Ub28C4xAuQQ8TuP3lUDMrE25gSN6QE5Xdm1eQYVApXVf3Efun0AxyGYOrSFxQASfk80+qYhA
            uoQJ3SoTl0B9gjaQVpBqQJdOohquC4NA
        - !!python/object/apply:builtins.slice
          - 0
          - 2
          - 1
        - 2
    - - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.base.Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id002
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 2
            - !!python/object/apply:numpy.dtype
              args:
              - O8
              - false
              - true
              state: !!python/tuple
              - 3
              - '|'
              - null
              - null
              - null
              - -1
              - -1
              - 63
            - false
            - - center
              - scale
          name: null
      - !!python/object/apply:pandas.core.indexes.base._new_Index
        - !!python/name:pandas.core.indexes.numeric.Int64Index ''
        - data: !!python/object/apply:numpy.core.multiarray._reconstruct
            args:
            - *id002
            - !!python/tuple
              - 0
            - !!binary |
              Yg==
            state: !!python/tuple
            - 1
            - !!python/tuple
              - 30
            - !!python/object/apply:numpy.dtype
              args:
              - i8
              - false
              - true
              state: !!python/tuple
              - 3
              - <
              - null
              - null
              - null
              - -1
              - -1
              - 0
            - false
            - !!binary |
              AAAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAUAAAAAAAAABgAAAAAAAAAH
              AAAAAAAAAAgAAAAAAAAACQAAAAAAAAAKAAAAAAAAAAsAAAAAAAAADAAAAAAAAAANAAAAAAAAAA4A
              AAAAAAAADwAAAAAAAAAQAAAAAAAAABEAAAAAAAAAEgAAAAAAAAATAAAAAAAAABQAAAAAAAAAFQAA
              AAAAAAAWAAAAAAAAABcAAAAAAAAAGAAAAAAAAAAZAAAAAAAAABoAAAAAAAAAGwAAAAAAAAAcAAAA
              AAAAAB0AAAAAAAAA
          name: series_id
    _typ: dataframe
    attrs: {}
  scale_by_group: false
  transformation: null
prediction_length: 28
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
sharing:
- true
- true
stack_types:
- trend
- seasonality
weight_decay: 0.001
widths:
- 256
- 1024
